site_name: vnpy非官方文档
pages:
- 主页: index.md
- 安装vnpy: install.md
- 接口列表、介绍: gateway.md
- 入门教程: tutorial.md
- Package参考: 
  - vnpy.evnet: package_reference/event.md
  - vnpy.trader.engine: package_reference/trader_engine.md
  - vnpy.trader.object: package_reference/trader_object.md
  - vnpy.trader.gateway: package_reference/trader_gateway.md
  - vnpy.trader.utility: package_reference/trader_utility.md
- Gateway参考:
  - 老虎证券(tiger): gateway_reference/tiger.md
  - 火币(huobi): gateway_reference/huobi.md
- 底层接口参考:
  - vnpy.api.websocket: base_reference/websocket_client.md
  - vnpy.api.rest: base_reference/rest.md
theme: readthedocs
